### ISSUE TITLE
Getting IndexError:list index out of range

### ISSUE THREAD

**Issue by ankush-grover-3pg** [efic1/zabbix_rds_template#1]
Hi,

I am running Zabbix 2.4.3 version on Centos 7 64-bit and I am getting below error when I try to run the rds_stats.py manually 

Traceback (most recent call last):
  File "rds_stats.py", line 73, in <module>
    average = res[-1]["Average"] # last item in result set
IndexError: list index out of range

The below error is in the zabbix logs

11009:20150302:153424.210 error reason for "dxxxxxxxxxx:rds_stats.py["--metric","WriteLatency","--instance-id","{HOST.HOST}","--access-key","{$AWS_ACCESS_KEY}","--secret-key","{$AWS_SECRET_KEY}"]" changed: Received value [Traceback (most recent call last):  File "/usr/lib/zabbix/externalscripts/rds_stats.py", line 73, in <module>    average = res[-1]["Average"] # last item in result setIndexError: list index out of range] is not suitable for value type [Numeric (float)]

What can be the issue?? Do let me know if you need any further information.

Thanks & Regards

Ankush Grover

**Comment by efic1** [comment]
Hi Ankush,
It means that the zabbix host name doesn't match the RDS DB Instance name (you can find it in the RDS instances list, or as the Endpoint URL prefix), it needs to perfectly match. Try executing the script manually:

rds_stats.py --metric WriteLatency --instance-id XYZ --access-key YYYY --secret-key ZZZ

Efi

**Comment by ankush-grover-3pg** [comment]
Same issue when I try to run it manually. I am using the full endpoint

xxxx-xxxxx.xxxxx.us-east-1.rds.amazonaws.com

**Comment by efic1** [comment]
So that's the problem - you just need to use the instance name, in the above case the first part of the endpoint hostname - xxxx-xxxxx

Efi

**Comment by ankush-grover-3pg** [comment]
Same issue only with the endpoint hostname..

**Comment by efic1** [comment]
Again, don't use the endpoint host name. You should use the instance name (which can be found as the first part of the hostname.
![screen shot 2015-03-02 at 2 12 11 pm](https://cloud.githubusercontent.com/assets/5286415/6440552/cb6d8554-c0e6-11e4-905f-179fc8aaa314.jpg)

**Comment by ankush-grover-3pg** [comment]
Yes, this is the same what I am using and I am getting the same error which I have mentioned earlier.

**Comment by efic1** [comment]
Which boto version are you using?
```
python
import boto
boto.Version
```

**Comment by efic1** [comment]
issue was fixed ea0dc22e8f30e90d758b3a944a47aebfee15e15c

It had to do with timezone differences

**Comment by ankush-grover-3pg** [comment]
Thanks for the fix. Now I can see the data in the zabbix.

Do you have plugin & template for collecting the EC2 CloudWatch metrics??

**Comment by Caddi1971** [comment]
Hi,
I've the same Problem with Zabbix Version 3.0.2
I use the DB Instance Name and get on Zabbix Frontend and withe the console:
File "./rds_stats.py", line 77, in <module>
    average = res[-1]["Average"] # last item in result set
IndexError: list index out of range

**Comment by alanwds** [comment]
Hi all,

I had the same issue using zabbix 3.2:

```
Traceback (most recent call last):
  File "./rds_stats.py", line 73, in <module>
    average = res[-1]["Average"] # last item in result set

```
>>> boto.Version
'2.47.0'

I'm completely that i'm using the DB instance name (not the full endpoint).

**Comment by phuzz** [comment]
I'm getting this error, but only with some (most) metrics. Others work fine.
eg, CPU utilisation is OK:
`./rds_stats.py --access-key KEY --secret-key KEY  --instance-id DBINSTANCE --region REGION --metric CPUUtilization`
Gives me: `4.4167`

However:
`./rds_stats.py --access-key KEY --secret-key KEY  --instance-id DBINSTANCE --region REGION --metric ReadIOPS`
Gives:
`Could not find datapoints for specified instance. Please review if provided instance (DBINSTANCE) and region (REGION) are correct
Traceback (most recent call last):
  File "./rds_stats.py", line 77, in <module>
    average = datapoints[-1].get('Average') # last item in result set
IndexError: list index out of range
`

(obviously the keys, instance and region are the same for both)
boto-2.48.0 boto3-1.7.3

**Comment by choiseockjun** [comment]
hi.
i have same problem.

Traceback (most recent call last):
  File "./rds_stats.py", line 73, in <module>
    average = res[-1]["Average"] # last item in result set

**Comment by EduardCloud** [comment]
Hi,
Late but.. seems ths metric names changed, updating metrics var with new and correct values did the trick.
